name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.4
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'skz_lookerstudio_visualization_bucket/table2'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
