name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync GCS Bucket
        uses: patrickwyler/gcs-bucket-sync-action@1.4
        with:
          secrets: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          bucket: 'skz_lookerstudio_visualization_bucket'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
